### ISSUE TITLE
Verification of jboss profile

### ISSUE THREAD

**Issue by stephan-sch** [eurodyn/QLACK1#1]
From the migrated Qlack code, profiles jboss and oracle have been removed.
-Oracle profile is obsolete as the value of the hibernate.dialect property in the persistences is now hardcoded.
-Jboss profile has to be examined.

**Comment by vlachouli** [comment]
The jboss profile is not needed anymore.
Please assign a value to this placeholder:
property name="hibernate.transaction.jta.platform" value="${transactionLookupClass}"

**Comment by imousmoutis** [comment]
JBoss Transaction class has been defined at the persistence.xml files of each fuse module.
