### ISSUE TITLE
Update OJDBC

### ISSUE THREAD

**Issue by stephan-sch** [eurodyn/QLACK1#3]
Currently qlack is using an older version of OJDBC driver. Please update with following:
```
<dependency>
  <groupId>com.oracle.database.jdbc</groupId>
  <artifactId>ojdbc8</artifactId>
  <version>18.3.0.0</version>
</dependency>

```

**Comment by imousmoutis** [comment]
This dependency is not needed any more, since the entities are provided within the source code and they are not auto-generated any more.
